/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CreateToyDialog: typeof import('./components/CreateToyDialog.vue')['default']
    DeleteToyTag: typeof import('./components/DeleteToyTag.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToyBox: typeof import('./components/ToyBox.vue')['default']
    ToyPad: typeof import('./components/ToyPad.vue')['default']
    ToyPadItem: typeof import('./components/ToyPadItem.vue')['default']
    ToyTag: typeof import('./components/ToyTag.vue')['default']
  }
}
